# Generated by Django 2.0 on 2017-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='', max_length=32)),
                ('port', models.CharField(default='', max_length=32)),
                ('db_name', models.CharField(default='', max_length=128)),
                ('username', models.CharField(default='', max_length=128)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
