# Generated by Django 2.0 on 2017-12-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oradb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topName', models.CharField(default='', max_length=32)),
                ('topId', models.BigIntegerField(max_length=16)),
                ('ralation_field', models.CharField(default='', max_length=32)),
                ('search_col', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='topTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('table_name', models.CharField(default='', max_length=32)),
                ('search_value', models.CharField(default='', max_length=128)),
                ('search_type', models.CharField(default='', max_length=8)),
                ('search_type_name', models.CharField(default='', max_length=32)),
                ('isUse', models.CharField(default='0', max_length=8)),
                ('relation', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
